# Generated by Django 3.2.11 on 2022-01-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='like',
            field=models.IntegerField(),
        ),
    ]
