# Generated by Django 3.2.11 on 2022-01-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('userPw', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('mbti', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('like', models.CharField(max_length=200)),
                ('heart', models.CharField(max_length=200)),
            ],
        ),
    ]
