# Generated by Django 4.0.1 on 2022-01-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=200)),
                ('registered_date', models.DateTimeField()),
                ('comment', models.CharField(max_length=200)),
                ('like', models.IntegerField()),
                ('img', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
            ],
        ),
    ]
