# Generated by Django 4.0.1 on 2022-01-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_board_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='board',
            name='comment',
        ),
        migrations.AlterField(
            model_name='board',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
